version: '3.9'
services:

  simulator:
    build: ./simulator
    ports:
      - "${SIMULATOR_PORT}:${SIMULATOR_PORT}"
    volumes:
      - ./simulator:/app
    environment:
      - SIMULATOR_PORT=${SIMULATOR_PORT}

  nodes:
    build: ./nodes
    volumes:
      - ./nodes:/app
    environment:
      - SIMULATOR_PORT=${SIMULATOR_PORT}
      - NODES_INTERVAL=${NODES_INTERVAL}

  scorer:
    build: ./scorer
    volumes:
      - ./scorer:/app
    environment:
      - SIMULATOR_PORT=${SIMULATOR_PORT}
      - SCORER_INTERVAL=${SCORER_INTERVAL}

  front:
    build: ./front
    ports:
      - "${FRONT_PORT}:${FRONT_PORT}"
    volumes:
      - ./front/src:/src
    environment:
      - FRONT_PORT=${FRONT_PORT}
