version: '3.9'
services:

  simulator:
    build: ./back
    command: bash -c "python3 simulator.py"
    ports:
      - "${SIMULATOR_PORT}:${SIMULATOR_PORT}"
    volumes:
      - ./back:/app
    environment:
      - SIMULATOR_PORT=${SIMULATOR_PORT}

  nodes:
    build: ./back
    command: bash -c "python3 nodes.py"
    volumes:
      - ./back:/app
    environment:
      - SIMULATOR_PORT=${SIMULATOR_PORT}
      - NODES_INTERVAL=${NODES_INTERVAL}

  scorer:
    build: ./back
    command: bash -c "python3 scorer.py"
    volumes:
      - ./back:/app
    environment:
      - SIMULATOR_PORT=${SIMULATOR_PORT}
      - SCORER_INTERVAL=${SCORER_INTERVAL}

  front:
    build: ./front
    command: bash -c "npm start"
    ports:
      - "${FRONT_PORT}:${FRONT_PORT}"
    volumes:
      - ./front/src:/src
    environment:
      - FRONT_PORT=${FRONT_PORT}
